reviews_test_data:
  image: mysql
  volumes:
    - ./docker/data/reviews.sql:/docker-entrypoint-initdb.d/reviews.sql

mysql_crosschx_global:
  image: mysql
  volumes_from:
    - reviews_test_data
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=reviews
